name: mbc_dash
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - networkx=3.1
  - pip
  - pip:
      - dash==2.14.1
      - dash-cytoscape==0.3.0
      - dash-bootstrap-components==1.4.1
      - plotly==5.15.0
      - gunicorn==23.0.0

